name: build

on:
  push:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Docker build & publish.
        run: |
          docker build -t pywharf/echo:latest .
          docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
          docker push pywharf/echo:latest
